// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8nlHQkcpIMzITBpDhvR3tFHF9YXiu5uQ',
    appId: '1:438957453959:web:fa6ca48de5c0e440ffbe22',
    messagingSenderId: '438957453959',
    projectId: 'grace-academy-873a7',
    authDomain: 'grace-academy-873a7.firebaseapp.com',
    storageBucket: 'grace-academy-873a7.firebasestorage.app',
    measurementId: 'G-GYGRHBNGD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlFegJbHCNIjah48OEjmgHnLS_Ga4yQ0',
    appId: '1:438957453959:android:95f60aa9245b7edcffbe22',
    messagingSenderId: '438957453959',
    projectId: 'grace-academy-873a7',
    storageBucket: 'grace-academy-873a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqeKMORqqF1VGV0hH3Tz_6YEt9XtYVo1U',
    appId: '1:438957453959:ios:5d6681cb023f794dffbe22',
    messagingSenderId: '438957453959',
    projectId: 'grace-academy-873a7',
    storageBucket: 'grace-academy-873a7.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
